version: '2'
services:
  app:
    image: alexcheng/magento2
    container_name: magento_app
    ports:
      - "80:80"
    links:
      - mysql
    env_file:
      - .env
    # volumes:
    #   - ./www:/var/www
  mysql:
    image: mysql:5.6.23
    container_name: magento_mysql
    env_file:
      - .env
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql:rw
volumes:
  db-data:
    driver: local