FROM appsvc/apps:apache-php-mysql-0.2
COPY ./httpd.conf /usr/local/httpd/conf/httpd.conf

# app
# ENV APP_HOME "/home/site/wwwroot/webapp"
# WORKDIR $DOCKER_BUILD_HOME
# RUN set ln -s $APP_HOME /var/www/wwwroot/webapp 
